(() => {
  function authModal(mode='join') {
    const overlay=document.createElement('div');overlay.className='amsn-modal-overlay';
    const join=mode==='join';
    overlay.innerHTML=`<div class="amsn-modal"><button class="amsn-close">×</button><h2>${join?'Join AMSN':'Sign in to AMSN'}</h2><p class="modal-note">Demo mode. The production version will connect this form to secure AMSN authentication.</p>${join?'<label>Full name<input class="auth-input" placeholder="Your name"></label>':''}<label>Email<input class="auth-input" type="email" placeholder="student@university.edu"></label><label>Password<input class="auth-input" type="password" placeholder="••••••••"></label>${join?'<label>Medical school / university<input class="auth-input" placeholder="University name"></label>':''}<div class="auth-note">🎓 Student verification can be completed after registration. It will not block initial access.</div><div class="modal-actions"><button class="amsn-secondary close-auth">Cancel</button><button class="amsn-primary submit-auth">${join?'Create account':'Sign in'}</button></div></div>`;
    document.body.appendChild(overlay);const close=()=>overlay.remove();overlay.querySelector('.amsn-close').onclick=close;overlay.querySelector('.close-auth').onclick=close;overlay.querySelector('.submit-auth').onclick=()=>{close();let t=document.getElementById('amsn-toast');if(t){t.textContent=join?'Account created — welcome to AMSN.':'Signed in — welcome back.';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}};
  }
  const style=document.createElement('style');style.textContent='.auth-input{display:block;width:100%;margin-top:6px;margin-bottom:12px;border:1px solid #d9e1e7;border-radius:8px;padding:11px;font:inherit}.amsn-modal label{display:block;font-size:12px;font-weight:700;color:#465666;margin-top:10px}.auth-note{background:#eaf6f3;border-radius:9px;padding:11px;font-size:12px;color:#365c54;margin-top:10px}.auth-actions{display:flex;gap:8px;margin-left:auto}.auth-actions button{border:1px solid #d7dee6;border-radius:8px;padding:8px 12px;font-weight:800;background:#fff;cursor:pointer}.auth-actions .join{background:#0b6b57;color:#fff;border-color:#0b6b57}';document.head.appendChild(style);
  window.addEventListener('DOMContentLoaded',()=>{const nav=document.querySelector('.toplinks');if(nav){const wrap=document.createElement('span');wrap.className='auth-actions';wrap.innerHTML='<button class="signin">Sign in</button><button class="join">Join AMSN</button>';nav.appendChild(wrap);wrap.querySelector('.signin').onclick=()=>authModal('sign');wrap.querySelector('.join').onclick=()=>authModal('join');}const avatar=document.querySelector('.avatar');if(avatar)avatar.title='Profile';});
})();