(() => {
  const API_BASE = window.AMSN_API_BASE || localStorage.getItem('amsn_api_base') || 'https://msn-bm0q.onrender.com/api';
  const token = () => localStorage.getItem('amsn_token');
  const api = async (path, options = {}) => {
    const headers = {...(options.headers || {}), 'Content-Type':'application/json'};
    if (token()) headers.Authorization = `Bearer ${token()}`;
    const r = await fetch(`${API_BASE}${path}`, {...options, headers});
    const d = await r.json().catch(() => ({}));
    if (!r.ok) throw new Error(d.error || 'Request failed');
    return d;
  };
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const css = document.createElement('style');
  css.textContent = `.amsn-verify-overlay{position:fixed;inset:0;background:#10203380;display:grid;place-items:center;padding:18px;z-index:200}.amsn-verify-box{width:min(620px,100%);background:#fff;border-radius:18px;padding:26px;box-shadow:0 24px 70px #0004;position:relative}.amsn-verify-box h2{margin:4px 0 8px}.amsn-verify-close{position:absolute;right:16px;top:12px;border:0;background:none;font-size:28px;cursor:pointer;color:#667584}.amsn-verify-eyebrow{font-size:11px;font-weight:850;letter-spacing:2px;color:#5b3fc8}.amsn-verify-note{color:#667584;line-height:1.55;font-size:14px}.amsn-verify-status{padding:14px;border:1px solid #e1e7ec;border-radius:10px;background:#f7f9fa;margin:16px 0}.amsn-verify-box label{display:block;font-weight:750;font-size:13px;margin:13px 0}.amsn-verify-box select,.amsn-verify-box textarea{display:block;width:100%;margin-top:7px;border:1px solid #d5dee5;border-radius:9px;padding:11px;font:inherit}.amsn-verify-actions{display:flex;justify-content:flex-end;gap:9px;margin-top:16px}.amsn-verify-primary,.amsn-verify-secondary{border:0;border-radius:9px;padding:11px 16px;font-weight:800;cursor:pointer}.amsn-verify-primary{background:#5b3fc8;color:#fff}.amsn-verify-secondary{background:#eef2f5;color:#344554}.amsn-verify-error{background:#fff0ef;color:#b42318;border-radius:9px;padding:10px;margin:10px 0}.amsn-verify-success{background:#ecfdf3;color:#067647;border-radius:9px;padding:10px;margin:10px 0}.amsn-verify-badge{font-size:11px;background:#ecfdf3;color:#067647;border-radius:999px;padding:4px 8px;font-weight:800}`;
  document.head.appendChild(css);
  function toast(msg){let el=document.getElementById('amsn-verify-toast');if(!el){el=document.createElement('div');el.id='amsn-verify-toast';el.style='position:fixed;bottom:80px;left:50%;transform:translateX(-50%);background:#102d3d;color:#fff;padding:10px 14px;border-radius:9px;z-index:210;font-size:13px';document.body.appendChild(el)}el.textContent=msg;setTimeout(()=>el.remove(),2600)}
  async function openVerification(){
    if(!token()){toast('Please sign in first.');return}
    const overlay=document.createElement('div');overlay.className='amsn-verify-overlay';
    overlay.innerHTML=`<div class="amsn-verify-box"><button class="amsn-verify-close">×</button><div class="amsn-verify-eyebrow">AMSN STUDENT VERIFICATION</div><h2>Verify your student status</h2><p class="amsn-verify-note">Verification builds trust across AMSN. You can browse while your request is pending. Verified students receive a verified badge and can use features that require verified student status.</p><div id="verifyStatus" class="amsn-verify-status">Loading verification status…</div><div id="verifyError" class="amsn-verify-error" style="display:none"></div><label>Verification method<select id="verifyMethod"><option value="university_email">University email</option><option value="student_id">Student ID / manual review</option><option value="institutional">Institutional verification</option></select></label><label>Evidence / note<textarea id="verifyEvidence" rows="4" placeholder="Provide a short note for the verification team. Do not enter passwords, national ID numbers, patient information, or other unnecessary sensitive data."></textarea></label><div class="amsn-verify-actions"><button class="amsn-verify-secondary" id="verifyClose">Close</button><button class="amsn-verify-primary" id="verifySubmit">Submit request</button></div></div>`;
    document.body.appendChild(overlay);
    const close=()=>overlay.remove();overlay.querySelector('.amsn-verify-close').onclick=close;overlay.querySelector('#verifyClose').onclick=close;overlay.onclick=e=>{if(e.target===overlay)close()};
    const status=overlay.querySelector('#verifyStatus'),error=overlay.querySelector('#verifyError'),submit=overlay.querySelector('#verifySubmit');
    try{const d=await api('/verification/status');const latest=d.requests?.[0];status.innerHTML=`<b>Status:</b> ${esc(d.status)} ${d.status==='verified'?'<span class="amsn-verify-badge">✓ Verified</span>':''}${latest?`<br><small>Latest request: ${esc(latest.method)} · ${esc(latest.status)}</small>`:''}`;if(d.status==='verified'){submit.disabled=true;submit.textContent='Verified ✓'}else if(latest?.status==='pending'){submit.disabled=true;submit.textContent='Request pending'}}catch(e){status.textContent='Could not load verification status.';error.textContent=e.message;error.style.display='block'}
    submit.onclick=async()=>{error.style.display='none';const evidence=overlay.querySelector('#verifyEvidence').value.trim();if(!evidence){error.textContent='Please provide a short note or evidence.';error.style.display='block';return}try{await api('/verification/request',{method:'POST',body:JSON.stringify({method:overlay.querySelector('#verifyMethod').value,evidence})});status.innerHTML='<b>Status:</b> pending<br><small>Your verification request has been sent to the AMSN verification team.</small>';submit.disabled=true;submit.textContent='Request submitted';toast('Verification request submitted.')}catch(e){error.textContent=e.message;error.style.display='block'}};
  }
  function install(){const avatar=document.querySelector('.avatar');if(avatar){avatar.title='Account & verification';avatar.addEventListener('click',e=>{if(token()){e.preventDefault();openVerification()}})}if(token()){const links=[...document.querySelectorAll('.menu a')];const profile=links.find(a=>a.textContent.toLowerCase().includes('profile'));if(profile){profile.addEventListener('click',e=>{e.preventDefault();openVerification()})}}}
  window.AMSNOpenVerification=openVerification;
  window.addEventListener('load',()=>setTimeout(install,300));
})();
